package ui;
import dao.NhanVienDAO;
import entity.NhanVien;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import utils.MsgBox;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author PC
 */
public class QuanLyNhanVien extends javax.swing.JDialog {
    int row = -1;
    /**
     * Creates new form QuanLyNhanVien
     */
    public QuanLyNhanVien(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        init();
    }
    public void init(){
        setLocationRelativeTo(this);
        setTitle("Nhân Viên");
                this.filltable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jpnTong = new javax.swing.JPanel();
        jpnDanhMuc = new javax.swing.JPanel();
        btnHoaDon = new javax.swing.JButton();
        btnViTri = new javax.swing.JButton();
        btnChucVu = new javax.swing.JButton();
        btnNhanVien = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnKho = new javax.swing.JButton();
        btnDoUong = new javax.swing.JButton();
        btnNhapHang = new javax.swing.JButton();
        jpnQuanLyTacVu = new javax.swing.JPanel();
        jpnQuanLyCaLamViec = new javax.swing.JPanel();
        lblMaNV = new javax.swing.JLabel();
        lblTenNV = new javax.swing.JLabel();
        txtMaNV = new javax.swing.JTextField();
        btnThemNV = new javax.swing.JButton();
        btnSuaNV = new javax.swing.JButton();
        btnNhapLai = new javax.swing.JButton();
        btnXoaNV = new javax.swing.JButton();
        txtTenNV = new javax.swing.JTextField();
        lblNgayVaoLam = new javax.swing.JLabel();
        lblDiaChi = new javax.swing.JLabel();
        lblChucVu = new javax.swing.JLabel();
        lblGioiTinh = new javax.swing.JLabel();
        txtNgayVaoLam = new javax.swing.JTextField();
        txtDiaChi = new javax.swing.JTextField();
        txtSoDT = new javax.swing.JTextField();
        lblSoDT = new javax.swing.JLabel();
        lblMatKhau = new javax.swing.JLabel();
        txtMatKhau = new javax.swing.JTextField();
        btnFirst = new javax.swing.JButton();
        btnPrev = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        rbtNu = new javax.swing.JRadioButton();
        rbtNam = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        txtKhuVuc = new javax.swing.JTextField();
        rdoQL = new javax.swing.JRadioButton();
        rdoNV = new javax.swing.JRadioButton();
        lblQuanLyCaLamViec = new javax.swing.JLabel();
        jpnBangKhuVuc = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblNhanVien = new javax.swing.JTable();
        txtTimKiem = new javax.swing.JTextField();
        lblTimKiem = new javax.swing.JLabel();
        btnTimKiem = new javax.swing.JButton();
        lbllogo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jpnTong.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jpnDanhMuc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý Chức Năng\n\n", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Segoe UI", 0, 17))); // NOI18N
        jpnDanhMuc.setName(""); // NOI18N

        btnHoaDon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/List.png"))); // NOI18N
        btnHoaDon.setText("HÓA ĐƠN");
        btnHoaDon.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnViTri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Smile.png"))); // NOI18N
        btnViTri.setText("CA LÀM VIỆC");
        btnViTri.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnChucVu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Certificate.png"))); // NOI18N
        btnChucVu.setText("CHỨC VỤ ");
        btnChucVu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnNhanVien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/User.png"))); // NOI18N
        btnNhanVien.setText("NHÂN VIÊN ");
        btnNhanVien.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnThongKe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Bell.png"))); // NOI18N
        btnThongKe.setText("THỐNG KÊ");
        btnThongKe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnKho.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Brick house.png"))); // NOI18N
        btnKho.setText("KHO");
        btnKho.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnDoUong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Yin-Yang.png"))); // NOI18N
        btnDoUong.setText("ĐỒ UỐNG");
        btnDoUong.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        btnNhapHang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Scroll list.png"))); // NOI18N
        btnNhapHang.setText("NHẬP HÀNG");
        btnNhapHang.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);

        javax.swing.GroupLayout jpnDanhMucLayout = new javax.swing.GroupLayout(jpnDanhMuc);
        jpnDanhMuc.setLayout(jpnDanhMucLayout);
        jpnDanhMucLayout.setHorizontalGroup(
            jpnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDanhMucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnDoUong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongKe, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapHang, javax.swing.GroupLayout.DEFAULT_SIZE, 163, Short.MAX_VALUE)
                    .addComponent(btnKho, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChucVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnViTri, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoaDon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnDanhMucLayout.setVerticalGroup(
            jpnDanhMucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDanhMucLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnViTri, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnDoUong, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnChucVu, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnKho, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnNhapHang, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(btnThongKe, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnQuanLyTacVu.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Quản lý tác vụ", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 18))); // NOI18N

        jpnQuanLyCaLamViec.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        lblMaNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMaNV.setText("Mã NV:");

        lblTenNV.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblTenNV.setText("Tên NV:");

        btnThemNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Add.png"))); // NOI18N
        btnThemNV.setText("THÊM ");
        btnThemNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnThemNV.setVerifyInputWhenFocusTarget(false);
        btnThemNV.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        btnThemNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnSuaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Edit.png"))); // NOI18N
        btnSuaNV.setText("SỬA ");
        btnSuaNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnSuaNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnNhapLai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Refresh.png"))); // NOI18N
        btnNhapLai.setText("NHẬP LẠI ");
        btnNhapLai.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnNhapLai.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        btnNhapLai.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        btnXoaNV.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Delete.png"))); // NOI18N
        btnXoaNV.setText("XÓA");
        btnXoaNV.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnXoaNV.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        lblNgayVaoLam.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblNgayVaoLam.setText("Ngày vào làm:");

        lblDiaChi.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblDiaChi.setText("Địa Chỉ:");

        lblChucVu.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblChucVu.setText("Chức vụ:");

        lblGioiTinh.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblGioiTinh.setText("Giới Tính:");

        lblSoDT.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblSoDT.setText("Số DT:");

        lblMatKhau.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        lblMatKhau.setText("Mật Khẩu:");

        btnFirst.setText("|<");
        btnFirst.setEnabled(false);

        btnPrev.setText("<<");
        btnPrev.setEnabled(false);

        btnNext.setText(">>");
        btnNext.setEnabled(false);

        btnLast.setText(">|");
        btnLast.setEnabled(false);

        buttonGroup1.add(rbtNu);
        rbtNu.setText("Nữ");

        buttonGroup1.add(rbtNam);
        rbtNam.setText("Nam");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel2.setText("Khu Vực:");

        buttonGroup2.add(rdoQL);
        rdoQL.setText("Quản Lý");

        buttonGroup2.add(rdoNV);
        rdoNV.setText("Nhân Viên");

        lblQuanLyCaLamViec.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblQuanLyCaLamViec.setText("Quản lý Nhân Viên");

        javax.swing.GroupLayout jpnQuanLyCaLamViecLayout = new javax.swing.GroupLayout(jpnQuanLyCaLamViec);
        jpnQuanLyCaLamViec.setLayout(jpnQuanLyCaLamViecLayout);
        jpnQuanLyCaLamViecLayout.setHorizontalGroup(
            jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnQuanLyCaLamViecLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(btnThemNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSuaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNhapLai, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnXoaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addComponent(lblSoDT)
                        .addGap(61, 61, 61)
                        .addComponent(txtSoDT))
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(btnFirst, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(btnPrev, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(56, 56, 56)
                        .addComponent(btnLast, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addComponent(lblMatKhau)
                        .addGap(36, 36, 36)
                        .addComponent(txtMatKhau))
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgayVaoLam)
                            .addComponent(lblChucVu)
                            .addComponent(lblDiaChi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addComponent(rbtNam, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtNgayVaoLam)
                            .addComponent(txtDiaChi)))
                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                        .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTenNV)
                                    .addComponent(lblMaNV)
                                    .addComponent(lblGioiTinh))
                                .addGap(39, 39, 39)
                                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtTenNV)
                                    .addComponent(txtMaNV)))
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(txtKhuVuc))
                            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(rbtNu, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                                        .addComponent(rdoQL, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(rdoNV, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(lblQuanLyCaLamViec)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQuanLyCaLamViecLayout.setVerticalGroup(
            jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyCaLamViecLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lblQuanLyCaLamViec)
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMaNV)
                    .addComponent(txtMaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTenNV)
                    .addComponent(txtTenNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGioiTinh)
                    .addComponent(rbtNam)
                    .addComponent(rbtNu))
                .addGap(19, 19, 19)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblChucVu)
                    .addComponent(rdoQL)
                    .addComponent(rdoNV))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNgayVaoLam)
                    .addComponent(txtNgayVaoLam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaChi)
                    .addComponent(txtDiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSoDT)
                    .addComponent(txtSoDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblMatKhau)
                    .addComponent(txtMatKhau, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFirst)
                    .addComponent(btnPrev)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addGap(18, 18, 18)
                .addGroup(jpnQuanLyCaLamViecLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSuaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnXoaNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhapLai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThemNV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jpnBangKhuVuc.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tblNhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ NV", "TÊN NV", "GIỚI TÍNH", "CHỨC VỤ", "NGÀY VÀO LÀM", "ĐỊA CHỈ", "SỐ ĐT", "MẬT KHẨU"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblNhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblNhanVienMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblNhanVien);
        if (tblNhanVien.getColumnModel().getColumnCount() > 0) {
            tblNhanVien.getColumnModel().getColumn(3).setResizable(false);
        }

        lblTimKiem.setText("Tìm Kiếm:");

        btnTimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Zoom.png"))); // NOI18N
        btnTimKiem.setText("Tìm Kiếm");

        javax.swing.GroupLayout jpnBangKhuVucLayout = new javax.swing.GroupLayout(jpnBangKhuVuc);
        jpnBangKhuVuc.setLayout(jpnBangKhuVucLayout);
        jpnBangKhuVucLayout.setHorizontalGroup(
            jpnBangKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBangKhuVucLayout.createSequentialGroup()
                .addGroup(jpnBangKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnBangKhuVucLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpnBangKhuVucLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(lblTimKiem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 540, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTimKiem)))
                .addContainerGap())
        );
        jpnBangKhuVucLayout.setVerticalGroup(
            jpnBangKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnBangKhuVucLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jpnBangKhuVucLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTimKiem)
                    .addComponent(btnTimKiem))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1)
                .addGap(9, 9, 9))
        );

        javax.swing.GroupLayout jpnQuanLyTacVuLayout = new javax.swing.GroupLayout(jpnQuanLyTacVu);
        jpnQuanLyTacVu.setLayout(jpnQuanLyTacVuLayout);
        jpnQuanLyTacVuLayout.setHorizontalGroup(
            jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jpnQuanLyCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnBangKhuVuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnQuanLyTacVuLayout.setVerticalGroup(
            jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnQuanLyTacVuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                        .addComponent(jpnQuanLyCaLamViec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jpnQuanLyTacVuLayout.createSequentialGroup()
                        .addComponent(jpnBangKhuVuc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18))))
        );

        lbllogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/coffee.png"))); // NOI18N
        lbllogo.setFocusable(false);

        javax.swing.GroupLayout jpnTongLayout = new javax.swing.GroupLayout(jpnTong);
        jpnTong.setLayout(jpnTongLayout);
        jpnTongLayout.setHorizontalGroup(
            jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpnTongLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(lbllogo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnQuanLyTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTongLayout.setVerticalGroup(
            jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTongLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpnTongLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lbllogo, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jpnDanhMuc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpnQuanLyTacVu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpnTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblNhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblNhanVienMouseClicked
        // TODO add your handling code here:
        if (evt.getClickCount() == 2) {
            this.row = tblNhanVien.getSelectedRow();
            this.edit();
        }
    }//GEN-LAST:event_tblNhanVienMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                QuanLyNhanVien dialog = new QuanLyNhanVien(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChucVu;
    private javax.swing.JButton btnDoUong;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnHoaDon;
    private javax.swing.JButton btnKho;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnNhanVien;
    private javax.swing.JButton btnNhapHang;
    private javax.swing.JButton btnNhapLai;
    private javax.swing.JButton btnPrev;
    private javax.swing.JButton btnSuaNV;
    private javax.swing.JButton btnThemNV;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JButton btnViTri;
    private javax.swing.JButton btnXoaNV;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel jpnBangKhuVuc;
    private javax.swing.JPanel jpnDanhMuc;
    private javax.swing.JPanel jpnQuanLyCaLamViec;
    private javax.swing.JPanel jpnQuanLyTacVu;
    private javax.swing.JPanel jpnTong;
    private javax.swing.JLabel lblChucVu;
    private javax.swing.JLabel lblDiaChi;
    private javax.swing.JLabel lblGioiTinh;
    private javax.swing.JLabel lblMaNV;
    private javax.swing.JLabel lblMatKhau;
    private javax.swing.JLabel lblNgayVaoLam;
    private javax.swing.JLabel lblQuanLyCaLamViec;
    private javax.swing.JLabel lblSoDT;
    private javax.swing.JLabel lblTenNV;
    private javax.swing.JLabel lblTimKiem;
    private javax.swing.JLabel lbllogo;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JRadioButton rdoNV;
    private javax.swing.JRadioButton rdoQL;
    private javax.swing.JTable tblNhanVien;
    private javax.swing.JTextField txtDiaChi;
    private javax.swing.JTextField txtKhuVuc;
    private javax.swing.JTextField txtMaNV;
    private javax.swing.JTextField txtMatKhau;
    private javax.swing.JTextField txtNgayVaoLam;
    private javax.swing.JTextField txtSoDT;
    private javax.swing.JTextField txtTenNV;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables

    boolean check(){
        String thongBao = "";
        //Kiểm tra mã nhân viên
        if (txtMaNV.getText().trim().isEmpty()) {
            thongBao += "Bạn chưa nhập Mã Nhân Viên\n";
        }
        //Kiểm tra Tên nhân viên
        if (txtTenNV.getText().trim().isEmpty()) {
            thongBao += "Bạn chưa nhập Tên Nhân Viên\n";
        }
        // Kiểm tra giới tính
        if (!rbtNam.isSelected() && !rbtNu.isSelected()) {
            thongBao += "Bạn chưa chọn giới tính\n";
        }
        // Kiểm tra chức vụ của nhân viên
        if (!rdoQL.isSelected() && !rdoNV.isSelected()) {
            thongBao += "Bạn chưa chọn chức vụ\n";
        }

        // Kiểm tra ngày vào làm của nhân viên (định dạng dd-MM-yyyy)
        String ngaySinh = txtNgayVaoLam.getText().trim();
        if (ngaySinh.isEmpty()) {
            thongBao += "Bạn chưa nhập ngày sinh\n";
        } else if (!ngaySinh.matches("\\d{2}-\\d{2}-\\d{4}")) {
            thongBao += "Ngày sinh phải có định dạng ngày-tháng-năm(dd-MM-yyyy)\n";
        } else {
            String[] parts = ngaySinh.split("-");
            int ngay = Integer.parseInt(parts[0]);
            int thang = Integer.parseInt(parts[1]);
            int nam = Integer.parseInt(parts[2]);

            if (thang < 1 || thang > 12) {
                thongBao += "Tháng không hợp lệ\n";
            } else {
                int soNgayTrongThang = 31;

                if (thang == 4 || thang == 6 || thang == 9 || thang == 11) {
                    soNgayTrongThang = 30;
                } else if (thang == 2) {
                    if (nam % 4 == 0 && (nam % 100 != 0 || nam % 400 == 0)) {
                        soNgayTrongThang = 29; // Năm nhuận
                    } else {
                        soNgayTrongThang = 28;
                    }
                }

                if (ngay < 1 || ngay > soNgayTrongThang) {
                    thongBao += "Ngày không hợp lệ cho tháng này\n";
                }
            }
        }
        if (txtDiaChi.getText().trim().isEmpty()) {
            thongBao += "Bạn chưa nhập Địa chỉ nhà ở của nhân viên\n";
        }
        // Kiểm tra SỐ ĐIỆN THOẠI
        String soDienThoai = txtSoDT.getText().trim();
        if (soDienThoai.isEmpty()) {
            thongBao += "Bạn chưa nhập số điện thoại\n";
        } else if (!soDienThoai.matches("\\d{10}")) {
            thongBao += "Số điện thoại phải có 10 chữ số\n";
        }
        // Kiểm tra bạn đã nhập mật khẩu hay chưa
        if (txtMatKhau.getText().trim().isEmpty()) {
            thongBao += "Bạn chưa nhập mật khẩu\n";
        }
        return true;
    }
    void filltable(){
        DefaultTableModel model = (DefaultTableModel) tblNhanVien.getModel();
        model.setRowCount(0);
        try {
            List<NhanVien> list = new NhanVienDAO().selectAll();
            for (NhanVien nv : list) {
                Object[] row = {
                    nv.getMaNV(),
                    nv.getTenNV(),
                    nv.isGioiTinh() ? "Nam" : "Nữ",
                    nv.isChucvu()? "Quản lí" : "Nhân viên",
                    nv.getNgayVaoLam(),
                    nv.getDiaChi(),
                    nv.getSoDT(),
                    //nv.getMatKhau(),
                    nv.getMatKhau().replaceAll(".", "*"), 
                    nv.getKhuVuc(),
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            MsgBox.alert(this, "Lỗi truy vấn");
        }
    }
    void setForm(NhanVien nv){
        txtMaNV.setText(nv.getMaNV());
        txtTenNV.setText(nv.getTenNV());
        rbtNam.setSelected(nv.isGioiTinh());
        rbtNu.setSelected(!nv.isGioiTinh());
        
        rdoQL.setSelected(nv.isChucvu());
        rdoNV.setSelected(!nv.isChucvu());
        

        java.util.Date ngayVaoLam = nv.getNgayVaoLam();
        if (ngayVaoLam != null) {
            SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
            String ngaySinhString = sdf.format(ngayVaoLam);
            txtNgayVaoLam.setText(ngaySinhString);
        } else {
            txtNgayVaoLam.setText(""); // Nếu ngày sinh là null, không gán giá trị
        }
        txtDiaChi.setText(nv.getDiaChi());
        txtSoDT.setText(nv.getSoDT());
        txtMatKhau.setText(nv.getMatKhau());
        txtKhuVuc.setText(nv.getKhuVuc());
    }
    
    NhanVien getForm(){
        NhanVien nv = new NhanVien();
        nv.setMaNV(txtMaNV.getText());
        nv.setTenNV(txtTenNV.getText());
        nv.setGioiTinh(rbtNam.isSelected());
        nv.setGioiTinh(rdoQL.isSelected());


        String ngayVaoLam = txtNgayVaoLam.getText();
        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
        try {
            java.util.Date utilDate = sdf.parse(ngayVaoLam); // Chuyển chuỗi thành java.util.Date
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime()); // Chuyển java.util.Date thành java.sql.Date
            nv.setNgayVaoLam(sqlDate);
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        nv.setDiaChi(txtDiaChi.getText());
        nv.setSoDT(txtSoDT.getText());
        nv.setMatKhau(txtMatKhau.getText());
        nv.setKhuVuc(txtKhuVuc.getText());

        return nv;
    }
        void edit() {
        String manh = (String) tblNhanVien.getValueAt(this.row, 0);
        NhanVien nh = new NhanVienDAO().selectById(manh);
        this.setForm(nh);

        //this.updateStatus();
    }

}
